import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';

import { MovieCard } from '../../components/movieCard';
import { Container, MovieList,SearchContainer, Title } from './styles';

export default function Busca({}) {
    const {query} = useRouter();

    const [searchText, setSearchText] = useState(query.id);
    const [movieList, setMovieList] = useState([]);

    useEffect(() => {
        handleSearch();
    },[])

      async function handleSearch () {
        if(searchText !== ''){
            const results = await fetch(`http://localhost:3000/api/search?q=${searchText}`);
            const json = await results.json();

            console.log(json);
            setMovieList(json.list);
        }
      }
          
  return (
    <Container >
      <Head>
        <title>FJ.Movie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Title> Perquisar por filmes</Title>

      <SearchContainer>
        <input type='text' 
          value={searchText} 
          onChange={e=>{setSearchText(e.target.value)}} 
        />   
        <button onClick={handleSearch}>Buscar</button>
      </SearchContainer>
        
        <MovieList>
            {movieList.map(item => {
              if(!item.poster_path) return
              return <li key={item.id}>
                <MovieCard 
                  id ={item.id}
                  title ={item.title}
                  poster_path ={item.poster_path}
                  original_title ={item.original_title}
                />
              </li>
            })}
            
        </MovieList>
      
    </Container>
  )
}


// export async function getServerSideProps(context){
//   // const res = await fetch(`http://localhost:3000/api/search?q=${context.params.id}`);
//   // const json = await res.json();
  
//   return { 
//     props:{
//       param: context.params.id
//     }
//   }
// }