import Head from 'next/head';
import Link from 'next/link';
import { Banner } from '../banner';
import { MovieCard } from '../movieCard';
import { Container, Title, MovieList } from './styles';

export default function Home({list}) {
  const index = Math.floor(Math.random() * list.length + 1);
  
  console.log(list);
  console.log(index);
  console.log(list[index].id);

  const {id, title, overview, poster_path} = list[index];

  return (
    <Container>
      <Head>
        <title>FJ.Movie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner
        id={id}
        title={title}
        description={overview}
        poster_path={poster_path}
      />
      <Title>Filmes em descaques</Title>
        <MovieList>
          {list.map((item, index) => {
            if(index >= 16) return
            return <li key={item.id}>
              <MovieCard 
                id={item.id} 
                poster_path={item.poster_path}
                original_title={item.original_title}
                title={item.title}
              />
            </li>
          })}
        </MovieList>    
      </Container>
  )
}