import Head from 'next/head';
import Link from 'next/link';

import styles from '../../styles/Home.module.css'

export default function MovieItem({info}) {
  console.log(info)
  return (
    <div className={styles.container}>
      <Head>
        <title>FJ.Movie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Detalhes do filme
        </h1>

        <h2>Nome: {info.title}</h2>
        <p><b>Pontuação: </b> {info.vote_average}</p>
        <p>Descrição: {info.overview}</p>

        <img 
            src={`https://image.tmdb.org/t/p/w300${info.backdrop_path}`} 
            width='400'
            alt={info.original_title}
        />

        <Link href="/busca">Filmes --> </Link>

        <ul>
          
        </ul>
      </main>
    </div>
  )
}

export async function getServerSideProps(context){
  const res = await fetch(`http://localhost:3000/api/movie/${context.params.id}`);
  const json = await res.json();

  return {
    props:{
      info: json.info
    }
  };
}